### ISSUE TITLE
700Mo only with firefox, don't know with others

### ISSUE THREAD

**Issue by JibsouX** [ZonD80/mega-downloader#1]
can't dll more than 700 mo

**Comment by ZonD80** [comment]
Check others. Check memory limitations for php on your server, and reply back.

**Comment by JibsouX** [comment]
My memory limit is :
memory_limit : 120M / 120M
not 700Mo i just dont know why it's doing that 701Mo = download error
and my max_execution_time : 50000 / 50000

**Comment by ZonD80** [comment]
Please give me link to file on mega with such problem.

**Comment by JibsouX** [comment]
like this one : http://pastebin.com/Fbzw0aKH file 7Go
my exemple : http://pastebin.com/PfV1u8vP
pastebins disponible for 1 week.

**Comment by ZonD80** [comment]
Ok I'll check on 5th of our October

**Comment by ZonD80** [comment]
*of October

**Comment by JibsouX** [comment]
okey thanks dude can i delete my message with the pastebin ?

**Comment by ZonD80** [comment]
No, I will need it when I will check code. You can send me it to my email.

**Comment by JibsouX** [comment]
i have send you the mail with the pastebin link so i will delete it from here (i dont want to be in clear here)

**Comment by ZonD80** [comment]
Please try now

**Comment by JibsouX** [comment]
mhh it seem's to work but not on may server... i have test it on an other server and it work sor i dont really understand why me because the other server has the same spec...
