### ISSUE TITLE
Vendor autoload is missing?

### ISSUE THREAD

**Issue by renekaigen** [ZonD80/mega-downloader#14]
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/mega/src/mega.class.php on line 5

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /Applications/MAMP/htdocs/mega/src/mega.class.php on line 5

**Comment by peter279k** [comment]
Hi @renekaigen  , you have to refer the Usage section in  README.md.
The vendor folder is generated by composer.phar. 
If you dont' want to use composer, you can consider the standalone branch.

**Comment by AndeYashwanth** [comment]
Fixed this in #24.
