### ISSUE TITLE
Stream download

### ISSUE THREAD

**Issue by Sarfroz** [ZonD80/mega-downloader#15]
Hi sir i wanted to implement this code with mine. But i would like to know that streaming download using your code will give me resume or not.

**Comment by ZonD80** [comment]
It is not possible ATM, because you need to store current offset somewhere to resume a download.

**Comment by Sarfroz** [comment]
http://www.zevera.com/ they give sir  but they donot store files, it
instantly starts

**Comment by peter279k** [comment]
Hi @Sarfroz , Do you mean the progress bar is like the following image?
```
# no max steps (displays it like a throbber)
  0 [>---------------------------]
  5 [----->----------------------]
  5 [============================]

# max steps defined
 0/3 [>---------------------------]   0%
 1/3 [=========>------------------]  33%
 3/3 [============================] 100%
```

**Comment by Sarfroz** [comment]
sir i give you example
Orignal Link--->>>
https://mega.co.nz/#!AIkCUSYR!_0pbIeu0mHsWTFXDfmMMNiSEL8p2qP6FQXF_1K-OOgA
download link using stream-->>
http://srvx.superdown.com.br/mega/AIkCUSYR/_0pbIeu0mHsWTFXDfmMMNiSEL8p2qP6FQXF_1K-OOgA/570924/TWD.6x13.part1.rar

as you said it not possible to have stream download  thats why i am sending
you.

**Comment by ZonD80** [comment]
Well. It downloaded file locally and then just providing you regular file download that can be resumed.

**Comment by Sarfroz** [comment]
but how can that work

**Comment by ZonD80** [comment]
It just regular file download from server. That's all.
