### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by 0utc0ntr0l** [ZonD80/mega-downloader#18]
it is not work

**Comment by ZonD80** [comment]
What exactly?

**Comment by 0utc0ntr0l** [comment]
it after i add
flush();
ob_flush();
sleep(1);
in progress function
			if($bytes_transferred > 0) {
				$length = (int)(($bytes_transferred/$filesize)*100);
				//echo ($bytes_transferred/1024), $filesize/1024 . "kb\n";
				echo $length . "%\n";
				    flush();
    ob_flush();
    sleep(1);
			}

**Comment by ZonD80** [comment]
This issue is related to progress display, not to code itself
