### ISSUE TITLE
Bandwidth error

### ISSUE THREAD

**Issue by Sarfroz** [ZonD80/mega-downloader#22]
Getting **HTTP/1.1 509 Bandwidth Limit Exceeded**

**Comment by ZonD80** [comment]
It is not related to this software. Perhaps you have reached mega account download limit?

**Comment by Sarfroz** [comment]
nope just tried with your test link worked fine and after that i tested with 1.9GB link it gave me error instantly. Also, i have a premium account of mega.co with 2TB traffic but I guess this software cannot be used with accounts ??

**Comment by Sarfroz** [comment]
oh no :( I hope you will add it in the future.
