### ISSUE TITLE
Work?

### ISSUE THREAD

**Issue by luisfigueroa34** [ZonD80/mega-downloader#25]
hi i wanted to ask if this code still works?

**Comment by ZonD80** [comment]
Yes, if you have all required extensions installed

**Comment by luisfigueroa34** [comment]
Another question, is it possible to use an unlimited account that I have by default in the code. I intend to use the links as a stream, if so and it has a value, could you let me know and we negotiate

**Comment by ZonD80** [comment]
AFAIR this software does not support authorization on mega, but you can contribute via pull request
