### ISSUE TITLE
How to download folders ?

### ISSUE THREAD

**Issue by Drezzler** [ZonD80/mega-downloader#3]
Hello @ZonD80 , do you know how can I download folders , With your class ?

Here is an example folder i want to download
`https://mega.nz/#F!7sUWDarI!PlPZJyGBfk9SCLMdHCt_4g`

**Comment by ZonD80** [comment]
You can not do this with this class.

**Comment by ZonD80** [comment]
I'm working on this right now

**Comment by ZonD80** [comment]
Easily with $megafile->download_zip();
https://github.com/ZonD80/mega-downloader/commit/634d7702edabac59a290531aed06f98e0fd16b6b
