### ISSUE TITLE
PHP Notice:  Undefined variable: buffer

### ISSUE THREAD

**Issue by peter279k** [ZonD80/mega-downloader#7]
Hi @ZonD80 , I think your mega.class.php has some bugs.

I noticed that it will output undefined message when I execute the example_file.php

```bash
PHP Notice:  Undefined variable: buffer in /home/webserver/mega-downloader/src/mega.class.php on line 203
PHP Notice:  Undefined variable: buffer in /home/webserver/mega-downloader/src/mega.class.php on line 206
```

Please fix it.

**Comment by ZonD80** [comment]
Just disable notice output in your php configuration. It's my ugly coding standard.

**Comment by peter279k** [comment]
Hi @ZonD80. Ok, I will fix some errors by myself. 

Do you mind that I modify code or participate in the project ?

**Comment by ZonD80** [comment]
No problem. That's why it is open source:) Create pull request and i will accept it.
